### ISSUE TITLE
Perf/resource consumption comparison per language

### ISSUE THREAD

**Issue by nulltoken** [Azure/azure-webjobs-sdk-script#1004]
I'm looking for some kind of benchmark that would allow one to compare perf/resource consumption for a similar Azure function implementation across languages (node vs c# for instance)?

Would any one exist?

**Comment by paulbatum** [comment]
You could start with the scenarios and execution tools found in: 
https://github.com/Azure/azure-functions-performance-test/tree/dev 

However be aware that what is available in this repo is a WIP. The performance tests we run internally are a combination of these scenarios/tools and some internal stuff.

Here are a few things to keep in mind when doing performance investigations on Azure Functions:
1. Do not leave the portal UI open on the function app during the run. Additional logging occurs when the UI is open.
2. Different languages have different performance characteristics, but because you pay for what you use, this means they also have different **billing characteristics**. To get the full picture you'll need to retrieve the measured usage. There is an ARM API you can use to retrieve this data. For info see here:
http://stackoverflow.com/questions/41128329/how-can-i-programmatically-access-azure-functions-usage-metrics

In terms of C# vs JS, we have observed results that are consistent with commonly held knowledge about the languages i.e. for CPU intensive operations, C# performs better / is less expensive.

Closing as answered.
