### ISSUE TITLE
No option for table binding to overwrite or replace row

### ISSUE THREAD

**Issue by jeremistadler** [Azure/azure-webjobs-sdk-script#1043]
#### Repro steps

I'm trying to add multiple rows with some of the rows already existing.

Bindings: 
```json
{
   "name": "outputTable",
   "type": "table",
   "connection": "storage",
   "tableName": "items",
   "direction": "out"
}
```

index.js
```javascript
context.bindings.outputTable = [1,2,3].map(itemId => {
   return {
      PartitionKey: 'numbers',
      RowKey: itemId,
      someColumn: 1
   };
});
```

The function will work the first time but will throw the second time with the error: ```The specified entity already exists```
without any way to catch it or prevent it.

No rows will be inserted if there is one row that exists.

#### Expected behavior

A way to overwrite, merge or ignore the rows that exists.

**Comment by mathewc** [comment]
The issue is that currently by design the underlying Table bindings in the core SDK only support "add new" semantics, not update. This feature request is tracked by an existing issue in that repo here: https://github.com/Azure/azure-webjobs-sdk/issues/919.

For now until the bindings are extended, you'll have to pull in and use the Azure SDK to perform your updates.
