### ISSUE TITLE
WebJobs SDK version used by portal

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk-script#1089]
Trying to understand what version of WebJobs SDK is used by default by Functions.

#### Repro steps

Code used to find the webjobs sdk version (could be eliminated so that auto-imported dependency version are discoverable as part of the portal experience - a feature request 😃).

```c#
var asm = Assembly.GetAssembly(typeof(Microsoft.Azure.WebJobs.Host.Bindings.IBinding));
var version = FileVersionInfo.GetVersionInfo(asm.Location).FileVersion;   
log.Info(version);
```

#### Expected behavior

Expected to see the latest stable (1.1.2).

#### Actual behavior

Reported version is 2.0.0

**Comment by fabiocav** [comment]
The runtime does indeed use 2.0.0.

I agree, it would be nice to have a better way to discover the version of shared assemblies. We need to think about how that would be handled to support extension provided assemblies as well.
One of the things we're also planning, to aid with local development and precompiled function scenarios, is to provide a meta package that brings the appropriate dependencies matching the runtime version.

**Comment by SeanFeldman** [comment]
@fabiocav considering that 2.0.0 is a beta, is it right to use it with the stable version of Functions?

**Comment by fabiocav** [comment]
2.0.0 is a beta for public consumption since some of the API surface (e.g. binding extensibility, some new features, etc.) is still in flux, not completely finished and likely to see breaking changes.

We manage those changes with the functions runtime internally, and in the context of Azure Functions, you're covered by the SLAs and support provided by the service.

**Comment by christopheranderson** [comment]
Closing as the question is resolved
