### ISSUE TITLE
Can't consistently use x-functions-key and x-functions-clientid headers instead of query string parameters

### ISSUE THREAD

**Issue by markheath** [Azure/azure-webjobs-sdk-script#1098]
Use of the `x-functions-key` and `x-functions-clientid` headers seems temperamental

#### Repro steps

1.  Create a generic webhook function

2. Create two new keys, a function key called client1 and an admin key called admin2

3. Verify that the function can be called using `/api/MyWebhook?clientid=client1&code=client1code`

4. Verify that the function can be called using `/api/MyWebhook?clientid=admin1&code=admin1code`

5. Now try to do the same thing using the `x-functions-key` and `x-functions-clientid` headers

#### Expected behavior

The function can be called successfully using headers instead of query string parameters

#### Actual behavior

A message is received saying "The WebHook verification request must contain a 'code' query parameter"

#### Known workarounds

It is possible to use just the master key in `x-functions-key`.

It is also possible to use the code query string and the `x-functions-clientid` header together

If the function type is a HTTP Trigger rather than a webhook, you can use the admin1 keys in `x-functions-key` and specifying `x-functions-clientid` seems not to be necessary

**Comment by christopheranderson** [comment]
@mathewc - could we handle this in the generic WebHook case?

**Comment by mathewc** [comment]
Yes this is an issue with WebHooks only currently - they don't support the `x-functions-key header`. This is because the `code` query parameter is pulled from the request not by us, but by the underlying WebHooks library we're using (e.g. code [here](https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Receivers/WebHooks/WebHookReceiver.cs#L203)).

Some options for us would be to clone the request and inject the param from the header before dispatch, or to find a way to wrap the receiver so we can intercept and override.
