### ISSUE TITLE
Issues loading assembly that has nuget dependency

### ISSUE THREAD

**Issue by sergsalo** [Azure/azure-webjobs-sdk-script#1262]
I have a function trigger that references shared assembly in ..\Shared\Common.dll. This Common.dll depends on nuget package HTTPDataCollectorAPI, v1.0.1. So, I added 

"dependencies": {
        "HTTPDataCollectorAPI": "1.0.1"
}

into project.json to my function trigger.

Now, when function runs it throws this error:

System.IO.FileNotFoundException: Could not load file or assembly 'HTTPDataCollectorAPI, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Ideas of what can be wrong with my references?  Or how can I fix this?

As the workaround I used to add a piece of code that references HTTPDataCollectorAPI in my run.csx and assembly was loaded, but now it doesn't work.

**Comment by sergsalo** [comment]
as a workaround I can trick it by copying HTTPDataCollectorAPI to shared folder and removing dependency on it from project.json file. But that seems like a bug.

**Comment by fabiocav** [comment]
@sergsalo apologies for the delayed response. This behavior is by design.
At a high level, this behaves this way because shared assemblies are scoped to the entire function app, not a particular function, and since they are loaded once per app and shared across functions, they do no rely on any individual function's references.

When using shared assemblies, the build output of those assemblies (typically what you'll have in your bin folder after building the project) should be deployed with them, including their dependencies.
