### ISSUE TITLE
Assembly Loading Into AppDomain Multiple Times

### ISSUE THREAD

**Issue by gardnerr** [Azure/azure-webjobs-sdk-script#1305]
Assemblies are being loaded multiple times into the AppDomain, which is creating issues with type comparisons / casting etc. 

This is only happening when deploying dependencies using the private deployment model. Shared assemblies seem to be unaffected.

Using the following code:
```
#r "Lib.PosLog.dll"
#r "Newtonsoft.Json.dll"
#r "Microsoft.ServiceBus"

using System;
using System.Threading.Tasks;
using System.Configuration;
using Newtonsoft.Json;
using Lib.PosLog;
using System.Reflection;

public static void Run(string message, TraceWriter log)
{
        var typeInPosLogDll = new TransactionDomainSpecific();
        Assembly.Load("Lib.PosLog");
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
}
```
When I inspect the assemblies array I see multiple copies of the Lib.PosLog assembly, each with am empty location and a codebase of Microsoft.Azure.WebJobs.Script.dll.

I ensured that only one copy of the assembly was deployed and still got the same behaviour.

**Comment by fabiocav** [comment]
@gardnerr sorry about the delayed response.

Yes, because of the current behavior of private assemblies (sige-by-side loading per function, reload with same identify on changes, etc.), this is expected. 

I do agree that this is problematic in many scenarios, and do have some thoughts on improvements we can make, so I've opened #1335 to track.
