### ISSUE TITLE
[TypeScript] - Importing modules outside of function root folder changes expected file structure

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#1520]
As an example, the following folder structure would cause this issue:
```
functionroot
├─── modules
│   ├─── modulea
│   └─── moduleb
└─── functiona
```

If `functiona` imports `modulea` with a relative reference (i.e. `'../modules/modulea'`), it causes the primary script file to be placed in a folder, matching the script/function folder name, in the output directory, when the runtime expects the script to be in the output directory.

**Comment by fabiocav** [comment]
@johnpapa FYI

**Comment by johnpapa** [comment]
Adding my experience from our email chat ....

-----

here is the summary of what happened, and what I think will work. I cannot exercise options 3 or 4, but you both may be able to do so.
 
 
… Nutshell … Azure Functions that use TypeScript and import modules have some “problems”. There is no good current answer, though I was able to get it to work … read on …
 
 
The Background:
When designing the structure of a function app using TypeScript, there may often be multiple functions in the function app. Each gets their own folder and a function.json file. For example:
 
/people /function.json
       /index.ts
 
/planets/function.json
        /index.ts
 
Each function is compiled using tsc in its folder. This means the people function is compiled in /people as the root and the planets function is compiled separately with /planets as the root/. These are compiled separately so each time a function’s code changes, only the code for that 1 function is recompiled (which is faster than waiting for 100 of them to recompile)
 
This produces an out folder that contains an index.js from which the function will run.
 
/people /function.json
       /index.ts
        /out/index.js
 
/planets/function.json
        /index.ts
        /out/index.js
 
The Problem:
 
It is natural that our customers may want a function app’s functions to share modules. For example, both people and planets functions may wan to import a shared filter module like this
 
import { filterList } from '../shared/filter'
 
from a folder structure like this …
 
/people /function.json
       /index.ts
 
/planets/function.json
        /index.ts
 
/shared /filter.ts
 
Now, when the planets or people function is compiled in the /planets folder, the out folder contents change so that all relative import paths will work. This means we end up with this output for …
 
 
/people /function.json
       /index.ts
        /out/people/index.js
        /out/shared/filter.js
 
/planets/function.json
        /index.ts
        /out/planets/index.js
        /out/shared/filter.js
 
/shared /filter.ts
 
Notice the index.js file is no longer in the root of the output folder. This causes a problem with Azure Functions as they require a the file  in the output folder to be in the root.
 
 
Options
1.       Don’t share files between the functions in a function app. This is unrealistic as many node apps share files.
2.       One function per app. This is unrealistic as well
3.       Make TypeScript’s compiled output flatten the root file … we were unable to do this as it changes the actual import code
4.       Add an index.js to the root that refers to the index.js in the subfolder … this would require a post compilation process (like gulp)
5.       Move all functions’ function logic to the same folder. Then have shared modules beneath that folder.
 
Option 5 is interesting and works …
 
 
/people /function.json
 
/planets/function.json
 
/api /people.ts
/api /planets.ts
/api /shared/ filter.ts
 
This produces the following output …
 
 
/api /out/ people.ts
/api /out/ planets.ts
/api /out/ shared / filter.ts
 
 
This allows each function to be compiled separately, yet still share the same shared modules. I was able to make option 5 work for my example.
 
 
Possible downsides
 
1  … when compiling people, the planet won’t be recompiled but the filter will be. Thus this could affect both functions, in this example.
 
 
2. The other problem with this is that it is entirely reasonable that many customers will struggle with this even if we document it. #3 or #4 above would resolve this and allow customers to have a more flexible structure.

**Comment by fabiocav** [comment]
We want to, as much as possible, keep the isolation between functions.

I'm experimenting with a couple of other options and will document them here if they are viable.

**Comment by fabiocav** [comment]
@johnpapa, I believe I have a pretty good working solution (running some additional tests with the proposed fix), but the key issue we are running into is that `rootDir` is implicitly set to the functions root directory when importing modules outside of the function folder, which doesn't happen in the module imports are not present, leading to the difference in behavior, breaking the runtime expectation.

The approach I'm validating is to, simply, explicitly specify the functions root directory as the `rootDir` in all cases, which will have a deterministic behavior, so we can change the runtime to look for the script in the new expected location (e.g. `<function_root>\myfunction\.output\myfunction\index.js`)
