### ISSUE TITLE
HttpTriggers can fire against disposed or uninitialized ScriptHosts

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#1537]
For 'normal' triggers, we stop all listeners before we dispose of a host, and they only start when the host has been fully initialized. But with HttpTriggers, we're always dispatching them to the currently set Instance, whether it's ready or not. This has manifested itself in a couple of race conditions that I've seen so far:

- It's possible to try to log with a disposed `LoggerFactory` as the host has been disposed, yet it is still set as the `Instance` property in `ScriptHostManager`. We'll be disabling our `LoggerFactory` disposal temporarily until we can fix the underlying problem.
- I've seen requests attempt to be made using a `DefaultTypeLocator`, which should never happen. This is because the request is coming in before the configuration is fully set -- we override this TypeLocator in Script.

We need to have a way to queue up HTTP traffic while we bring up a new host, then let it execute against that host.

**Comment by fabiocav** [comment]
For additional context. Today, the `WebScriptHostManager` directly pushes the request against the current instance by directly accessing the instance property, which may, for different reasons, reference an invalid, not ready or disposed host.
One proposed solution is to queue up those requests here instead and have a proper listener that dequeues them. We may want to turn the `HttpRequestManager` into a long living service (that is kept between host restarts) making the appropriate changes to that it is injected by the runtime and used by the HTTP binding, since the manager already handles request queuing.
