### ISSUE TITLE
function app http trigger powershell- function runs twice

### ISSUE THREAD

**Issue by RashmiPankaj** [Azure/azure-webjobs-sdk-script#1543]
I created http trigger powershell template. The function is provisioning vm. The issue I am facing is even my vm gets created in 3-4 mins and starts running in portal. The function never ends it executes the script twice as I can check the log with error as resource with ... name already exists do you want to overwrite and finally it shows timeout after 5 mins. 

![azfunc](https://cloud.githubusercontent.com/assets/4704225/26480928/255f954c-41fb-11e7-8864-2ff5e8d4db4c.png)

**Comment by christopheranderson** [comment]
@tohling - can you look into why we might have executed twice?

@RashmiPankaj - I would recommend you don't have your function run the entire time you're waiting for the VM to run. You're being charged for all that intermediate time, which isn't necessary.

I'd go with two Functions:
1. Starts the VM creation workflow in ARM and enqueues a message, with the operation id to get status, with a visibility time 3-4 minutes in the future.
2. The Queue triggered function listening on the queue. It checks the status, and if it is still processing, it reenqueues a minute or two in the future. If it is done, it then does whatever the next steps you would need. 

If there is additional work, I'd even consider using another Function with a queue to make your workflow nice and reliable. This should save you a bunch of processing time and it is much more reliable.

**Comment by tohling** [comment]
@RashmiPankaj, I have seen the PowerShell VM creation script take 7-9 mins to complete.   The script interacts with many sub-systems and execution time varies depending on the response times from those individual requests.  With the current max timeout of 5 mines (soon to be 10 mins), the Function execution will timeout.  The fact that the VM is accessibly via portal is independent of how long it takes for the VM creation script to complete its execution.  I have experienced situations where the VM is showing a "Ready" state in the Portal only to be rebooted subsequently because the provisioning process is in fact still on-going.

Understandably it is wasteful to try to recreate a VM that has already been created.  To mitigate, just check for the existence of the VM using the `Get-AzureRmVM `cmdlet before you execute the create command.

**Comment by tohling** [comment]
Closing issue due to lack of response from customer.  @RashmiPankaj, kindly reopen if you have further questions.
