### ISSUE TITLE
Security issue in Node v6.5.0 LTS (update to V6.11.1 LTS required)

### ISSUE THREAD

**Issue by yvele** [Azure/azure-webjobs-sdk-script#1682]
# Constant Hashtable Seeds vulnerability

Node V6.x LTS versions are vulnerable to some major security issues:
 - https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/
 - [Effective_DoS_on_web_application_platforms.pdf](https://events.ccc.de/congress/2011/Fahrplan/attachments/2007_28C3_Effective_DoS_on_web_application_platforms.pdf) (original paper)

> Updates are now available for all active Node.js release lines as well as the 7.x line. These include the fix for the **high severity vulnerability** identified in the initial announcement, one additional lower priority Node.js vulnerability in the 4.x release line, as well as some lower priority fixes for Node.js dependencies across the current release lines.
> 
> We recommend that users of all these release lines upgrade as soon as possible.

Are you considering upgrading to [6.11.1](https://nodejs.org/en/blog/release/v6.11.1/)?

----

PS: ASP.NET ~~is~~ was also vulnerable https://technet.microsoft.com/library/security/2659883 (and also [Python, Java, etc.](https://events.ccc.de/congress/2011/Fahrplan/attachments/2007_28C3_Effective_DoS_on_web_application_platforms.pdf))

**Comment by paulbatum** [comment]
Yes we intend to upgrade to 6.11.1 however this upgrade is more complicated in the case of Functions because we get our version of node.js from [edge](https://github.com/tjanczuk/edge), which has not been updated to 6.11.1 yet. I've reached out to Tomasz (the owner of edge) but I don't have an ETA yet for when the entire upgrade will be complete.

There are two factors to keep in mind that minimize the impact of this vulnerability in the context of Azure Functions:
1. Functions always uses ASP.NET as the HTTP application framework regardless of the language used to write the function, and ASP.NET is already patched for this vulnerability as it was initially disclosed in 2011 (I think it would make more sense in your comment above to say that ASP.NET _was_ vulnerable). 
2. For a JavaScript HTTP triggered function with auth enabled, no JavaScript is ever executed for a request that fails authentication. So there is no possibility of there being an unauthenticated attack vector here.

**Comment by yvele** [comment]
Related to https://github.com/Azure/app-service-announcements/issues/19

**Comment by rcarmo** [comment]
I'd love to have 8.1.4 support under Azure Functions - maybe this would be a good timing to move to the latest LTS?

**Comment by yvele** [comment]
## [Edge v8.2.1](https://github.com/tjanczuk/edge/releases/tag/v8.2.1)

>  - Add support for Node.js 8.2.1
>  - Remove support for Node.js 4.x and 5.x
>  - **Upgrade Node.js 6 to 6.11.2** (security patches)
>  - Upgrade Node.js 7 to 7.10.1 (security patches)

**Comment by christopheranderson** [comment]
We'll be updating to 6.11.1 in the next release. @mamaso has checked it in recently.

**Comment by rcarmo** [comment]
Hmmm. No chance of being able to specify Node 8, then?

**Comment by paulbatum** [comment]
@rcarmo No. Right now we don't have the capability of allowing a single version of functions to use different versions of node JS. Our next major version release will not use Edge.js (see https://github.com/Azure/azure-webjobs-sdk-script/issues/1319) and the approach we're using may allow us to side-by-side multiple versions of node (we still need to discuss this further).

**Comment by Schaemelhout** [comment]
@paulbatum What do you mean with "a single version of functions to use different versions of node JS"? I'm struggling to understand why a function app can't target any (supported) version of Node.js (>= v6.5.0)

**Comment by mamaso** [comment]
Any 1.x functions host uses a compiled node dll, not the usual node.exe. In particular, we use edge.js. Essentially, it's like we're using a native modules in order to run node, so we can't change versions without recompiling.

The newly announced 'beta' dotnet core functions host has moved away from this model. It calls node exe directly, based on the version of node that is on the PATH - in azure, you can change this via WEBSITE_DEFAULT_NODE_VERSION app setting.

Closing this issue as we have upgraded the version of node used by the 1.0 host.
