### ISSUE TITLE
Disable function not working on portal for functions created from visual studio 2017.

### ISSUE THREAD

**Issue by Avinash74** [Azure/azure-webjobs-sdk-script#1846]
i have created functions from visual studio 2017 update 3 (15.3.2).  When i try to disable the function from portal its not working.

Scenario - 
i have 40 functions. After the deployment i have to start the functions at the specific sequence ( Suppose 2,5,6,8...) and when function 2 execution completes i have to disable it. 
This is not possible for me now.

**Comment by lindydonna** [comment]
This is by design. If you want to dynamically enable/disable, you should use an app setting for the disable value, and update the app setting instead.

For instance

```csharp
[Disable(Func1Disable)]
public static void MyFunc(...)
```

In the future, we'll move enable/disable outside of function.json, at which point the app setting would not be necessary. Please watch https://github.com/Azure/azure-webjobs-sdk-script/issues/1331 for updates.

**Comment by nukec** [comment]
I published one function from Visual Studio and it locked all other 20 functions. How is this by design?? What can I do to develop functions from azure again?

**Comment by TrevorMullen** [comment]
on this page: https://github.com/Azure/azure-functions-ux/issues/1712 I found that:
If, when published, all other apps are locked to read-only mode.
	if you want to work around this, you can delete the "generatedBy" property in your function.json(s). 
	You can do that from: functionApps => <AppName> => Platform Features => App Service Editor

**Comment by Frankwayne** [comment]
@TrevorMullen   deleting the generatedBy does not work.  I have  deleted all the generatedBy properties in my azure function app and the function still run.

**Comment by TrevorMullen** [comment]
Hi @Frankwayne, yes the functions are supposed to run.  (Unless you can disable them from the menu.)
what @nukec said was that uploading locked all the other functions so they can't be edited. 
What I said was that if you remove the generatedBy on the functions uploaded from Visual studio, you unlock the other functions so that they can be edited again.

**Comment by paulbatum** [comment]
As was described above, for functions authored in VS you need to disable them via attributes.

You should avoid mixing a combination of functions written in the portal and functions written in VS within the same function app. This leads to problems like the issue you described where you are unable to edit the portal based functions.

Generally any workaround involving the deletion of the generatedBy metadata is not recommended. You are likely to run into other issues if you do this. We deliberately lock the UX based on that metadata because as you have discovered, changing the disable state in the portal does not work for functions written in VS. It would be pointless to provide an editing experience that does not work and thats why we go into readonly mode.

To get back into a good state, I suggest you manually delete the folders containing the functions you authored with Visual Studio. You can do this via `https://<appname>.scm.azurewebsites.net/debugconsole`, then go to site/wwwroot and you should see the folders and be able to delete them.

**Comment by antlhuede** [comment]
I think the question of "How is this by design" still applies, and no one has actually answered that.

Pretty ridiculous to lock out all other function types, seems like a lazy oversight more than anything.

**Comment by paulbatum** [comment]
@antlhuede please see here for the most up to date info:
https://docs.microsoft.com/en-us/azure/azure-functions/disable-function

In functions V2 we introduced a mechanism based on app settings that allows you to disable functions without requiring usage of the disabled attribute discussed above.

The behavior described above is "by design" for V1 because that is how disabling was implemented in V1 and we don't intend to change it.

**Comment by vinothrao** [comment]
> As was described above, for functions authored in VS you need to disable them via attributes.
> 
> You should avoid mixing a combination of functions written in the portal and functions written in VS within the same function app. This leads to problems like the issue you described where you are unable to edit the portal based functions.
> 
> Generally any workaround involving the deletion of the generatedBy metadata is not recommended. You are likely to run into other issues if you do this. We deliberately lock the UX based on that metadata because as you have discovered, changing the disable state in the portal does not work for functions written in VS. It would be pointless to provide an editing experience that does not work and thats why we go into readonly mode.
> 
> To get back into a good state, I suggest you manually delete the folders containing the functions you authored with Visual Studio. You can do this via `https://<appname>.scm.azurewebsites.net/debugconsole`, then go to site/wwwroot and you should see the folders and be able to delete them.

On the same line why can't we disable the status toggling also when the function is from VS? it is confusing.

**Comment by paulbatum** [comment]
The portal does disable this status toggling. To double check, I made a V1 function app, deployed from VS. See these screenshots:

![image](https://user-images.githubusercontent.com/10663/53929905-3e60dd00-4044-11e9-8a3e-fdb679af05df.png)

![image](https://user-images.githubusercontent.com/10663/53929920-47ea4500-4044-11e9-973f-9a978eed8376.png)

The toggle is disabled in both views. If you follow the same steps you should get the same behavior.

**Comment by vinothrao** [comment]
But for V2 it is enable even deployed from VS. Is it the correct behaviour? Am i missing some point?

![v2-enable](https://user-images.githubusercontent.com/5294130/53935597-fafe8100-40cc-11e9-9906-5842cb0ca1e1.PNG)

**Comment by paulbatum** [comment]
Yes, in V2 we improved the system so that functions written in VS can be disabled through the portal. All of this is explained in this doc:
https://docs.microsoft.com/en-us/azure/azure-functions/disable-function
