### ISSUE TITLE
Warnings for unused bindings not appearing

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#186]
Steps to reproduce:
1. Create queue trigger function
2. Go to integrate tab, add blob output and save
3. Go back to develop tab.
4. Drop message in queue and see log update with function execution (this step should be optional I think)

Expected result: Logs show warning indicating that output binding argument is missing
Actual result: No warning appears in logs.

**Comment by mathewc** [comment]
What language are you using? In the case of C#, I could see us logging an error if you haven't included the binding in your function signature.

For all the other loosely typed languages, we don't really know if you've used it in your code. Since actually writing to the output binding isn't required (e.g. scenarios where you only conditionally produce output), we can't use that as an indicator.

**Comment by paulbatum** [comment]
Yes this was C#

**Comment by christopheranderson** [comment]
This should work. If it repros, we should fix it.
