### ISSUE TITLE
[Core] NRE when using an invalid method for entryPoint

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1867]
I had the wrong namespace in my manually-authored function.json, and I just got a NRE when running the Core Tools:

```
Listening on http://localhost:7071/
Hit CTRL-C to exit...
Object reference not set to an instance of an object.
```

**Comment by mamaso** [comment]
@MikeStall this may be an issue in full framework as well:

> System.NullReferenceException : Object reference not set to an instance of an object.
>    at Microsoft.Azure.WebJobs.Script.UserTypeScanner.GetPossibleExtensionAssemblies(IEnumerable`1 userTypes) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\UserTypeScanner.cs : 21
>    at Microsoft.Azure.WebJobs.Script.ScriptHost.LoadDirectlyReferencesExtensions(IEnumerable`1 userTypes) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 718
>    at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 505
>    at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(IScriptHostEnvironment environment,IScriptEventManager eventManager,ScriptHostConfiguration scriptConfig,ScriptSettingsManager settingsManager) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 937

**Comment by fabiocav** [comment]
It does and it's not clear what the problem is.

**Comment by davidebbo** [comment]
I ran into this as well. In mu case, it seems the cause is that when you delete a Function in VS and republish, the old function folder doesn't get removed, so it ends up with a function.json that points to nothing. e.g. I have:

```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "timerTrigger",
      "schedule": "11 14 17 * * *",
      "useMonitor": true,
      "runOnStartup": false,
      "name": "myTimer"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\FunctionAppVS2017.dll",
  "entryPoint": "FunctionAppVS2017.MyTimer.Run"
}
```

But `FunctionAppVS2017.MyTimer.Run` no longer exists in the assembly.

We need to fix the runtime so it quietly ignores that function and doesn't fail the whole startup (in addition to fixing VS publish: https://github.com/Azure/Azure-Functions/issues/469).
