### ISSUE TITLE
Node Function App Not Parsing JSON Correctly

### ISSUE THREAD

**Issue by hoo29** [Azure/azure-webjobs-sdk-script#2111]
#### Investigative information

- Timestamp: 2017-11-08T19:05:36.192
- Function App version (1.0 or 2.0-beta): ~1
- Invocation ID: d9659aa0-10e2-4f4d-9d80-14e6e6203d22
- Region: UK South

#### Repro steps

Create a Node v6 function app that has the following code:
```javascript
module.exports = function (context) {

    context.log(context.req.rawBody);
    context.log(context.req.body);
    context.log(JSON.parse(context.req.rawBody));   
    
    context.res = {
        body: context.req.body
    };

    context.done();
};
```

POST the following JSON at it with the Content-Type header set to application/json:
```javascript
{ "time" : "2017-12-09T16:45:30.835Z", "bool": false, "str": "abc", "number": 123 }
```

#### Expected behaviour

The logs to show:
```javascript
{ "time" : "2017-12-09T16:45:30.835Z", "bool": false, "str": "abc", "number": 123 }
{ time: '2017-12-09T16:45:30.835Z',  bool: false, str: 'abc', number: 123 }
{ time: '2017-12-09T16:45:30.835Z',  bool: false, str: 'abc', number: 123 }
```

As in, context.req.body to give the same result as JSON.parse(context.req.rawBody).

#### Actual behavior

The logs show:
```javascript
{ "time" : "2017-12-09T16:45:30.835Z", "bool": false, "str": "abc", "number": 123 }
{ time: 2017-12-09T16:45:30.835Z,  bool: false, str: 'abc', number: 123 }
{ time: '2017-12-09T16:45:30.835Z',  bool: false, str: 'abc', number: 123 }
```

Note the time value of the second log (context.req.body) is not quoted. 

#### Known workarounds

Don't rely on context.req.body and instead use JSON.parse(context.req.rawBody).

#### Related information 

This becomes an issue when you are sending the JSON to other services as it is malformed. It is not just context.log displaying it incorrectly.

**Comment by cgillum** [comment]
@christopheranderson this is interesting and you may want to take a look.

**Comment by christopheranderson** [comment]
This is because we are parsing the `context.req.body` object with JSON.NET and serializing over to Node.js, which has datetime handling. `JSON.parse(context.req.rawbody)` does not parse dates. This is a weird case where JSON.NET's JSON parsing support is richer than the built in JavaScript method. 

If you want to get an equivalent value from `context.req.body`, you should be able to do `JSON.stringify(context.req.body)` which will `toString` the date object.

You can see [this](https://stackoverflow.com/questions/4511705/how-to-parse-json-to-receive-a-date-object-in-javascript) question on Stack Overflow with a simple way to enrich JSON.Parse to properly format datetimes. 

Closing as by-design.

Note for myself: We might have different behavior here in v2, since we changed how serialization works.

**Comment by ahmadawais** [comment]
@christopheranderson I have a similar issue where a 3rd party webhook sends data as json and I have to do this

```js
const log = context.log;
  log('——— req.query ——— ', req.query);
  const sale_gross = req.query.p_sale_gross || '0';
  const earnings = JSON.parse(req.query.p_earnings)['16413'] || '0';
```

error I get is this

```sh
[Error] Exception while executing function: Functions.hello. mscorlib: SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at module.exports (D:\home\site\wwwroot\hello\handler.js:4:25)
    at D:\Program Files (x86)\SiteExtensions\Functions\1.0.11702\bin\azurefunctions\functions.js:106:24.
2018-05-09T22:52:07.274 [Error] Function completed (Failure, Id
```

Any help?
