### ISSUE TITLE
cosmosDBTrigger causes overload on the leases collection

### ISSUE THREAD

**Issue by rtyler** [Azure/azure-webjobs-sdk-script#2144]
#### Investigative information

Please provide the following:

- Timestamp: 2017-11-20T04:50:18.383
- Function App version (1.0 or 2.0-beta): 1.0.11388.0
- Function App name: b985666c-b30b-4c15-b796-8968b1bbd444 in 
- Function name(s) (as appropriate):
- Invocation ID: `b985666c-b30b-4c15-b796-8968b1bbd444` `3d1cacd1-2d3f-47a3-b79d-9cb0d4cc6067`
- Region: West US 2

#### Repro steps

I'm not sure how to reproduce this other than "use the `cosmosDBTrigger`".

I deployed a JavaScript-based Function this evening which uses the `cosmosDBTrigger` and I'm seeing an **absurd** number of requests to the Azure CosmosDB's "leases" collection. The collection was automatically created by the tirgger binding. See this spike:

![selection_245](https://user-images.githubusercontent.com/26594/33002965-8e182782-cd6c-11e7-886f-0a36c80e0438.png)

#### Expected behavior

The collection which the function is triggering off of only has ~6k records in it, and generally speaking less than 50 new records are added an hour.

I would expect the leases traffic to not exceed my RU/s on CosmosDB and be within an appropriate order of magnitude 😈 

#### Actual behavior

The Function itself has only been invoked 88 times at my current count, so for 88 Function invocations we're looking at **thousands** of requests to CosmosDB.

#### Related information 

**function.json**

```json

{
  "disabled": false,
  "bindings": [
    {
      "direction": "in",
      "type": "cosmosDBTrigger",
      "databaseName" : "db",
      "collectionName" : "someColl",
      "connectionStringSetting" : "COSMOSDB_PAGES",
      "createLeaseCollectionIfNotExists": true,
      "name": "coll"
    },
    {
      "direction": "out",
      "type": "eventHub",
      "name": "events",
      "path": "some-eventhub",
      "connection": "EVENTHUB"
    }
  ]
}
```

**Comment by ealsur** [comment]
Hi @rtyler Is your Function in Consumption Mode or running in an App Service? If it is the later, how many instances of the App Service are?

**Comment by rtyler** [comment]
The function is on a Consumption plan

**Comment by ealsur** [comment]
Thanks @rtyler 

From the metrics I can see the RU usage is less than 200 RU/s per hour, which is not high. Are you concerned about the amount of Requests made to the collection?

**Comment by rtyler** [comment]
@ealsur yeah, the number of requests made to the collection concerns me, mostly because I don't know how to model this behavior for any capacity/cost planning. I disabled an upstream Function which was pushing writes into Cosmos and the traffic on the `leases` collection remained at ~8K/hour

![selection_257](https://user-images.githubusercontent.com/26594/33137458-df1f5230-cf5c-11e7-88d7-05c8ba1765bd.png)

The spike to the right on the graph represents me re-enabling the upstream function, which added approximately 150 records, _apparently_ resulting in 2k/hour additional requests on the `leases` collection.

Since the behind the scenes isn't fully open to me, it's hard to tell whether this is a bug or a mismatched set of user expectations 😄. My end goal here is to better understand how I should be capacity planning for these Azure Functions interacting with Cosmos

**Comment by ealsur** [comment]
Just so in case you want to delve into the logic, the code of the Trigger is [here](https://github.com/Azure/azure-webjobs-sdk-extensions/tree/dev/src/WebJobs.Extensions.CosmosDB/Trigger). The Trigger internally uses the Azure Cosmos DB Change Feed Processor, the code is also available [here](https://github.com/Azure/azure-documentdb-dotnet/tree/master/samples/ChangeFeedProcessor).

The amount of requests is not really out of what is expected, in a Consumption Plan scenario, the Functions runtime will test every 10 seconds to see how much pending work there is, that test equals at least 2 requests (more if the amount of Partition Key Ranges in your monitored collection is greater than 1, because the leases get created per PK Range), so that's 720 requests in an hour.

The Function itself uses a polling mechanism over the [Change Feed](https://docs.microsoft.com/azure/cosmos-db/change-feed) every 5 seconds or less to check for new changes. The leases are kept renewed every 17 seconds by default, so that adds a couple of other hundred requests per hour (~200) which will vary if your monitored collection has more Partition Ranges.

When new changes happen, the leases get checkpointed, which add more requests (depends on the frequency of your updates).

What's more important is the amount of RU/s consumed, which by the metrics is low (<200). Requests will get throttled if the RU consumption goes over the provisioned one. 

In your request chart you can see that all requests are a HTTP 200 (throttled requests are HTTP 429).

**Comment by paulbatum** [comment]
@ealsur thanks for the info on this! @rtyler can we close this?

**Comment by rtyler** [comment]
@paulbatum Yeah I think that's reasonable. I would recommend passing this off internally to some of the folks responsible for the [azure functions docus](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-documentdb) to improve that content to explain a bit more about "what's expected" for silly users like me 😄 

Thanks for the info @ealsur
