### ISSUE TITLE
Azure Function not triggered by the Queue until I log into the Portal

### ISSUE THREAD

**Issue by shather** [Azure/azure-webjobs-sdk-script#2159]
This is the same issue as #1858 , however it was closed. Basicly, function dequeue items only if im looking at it from portal azure. Function has been precompiled in VS2017. Im using consumption plan

this data is collected from sucessful invocation, however function didn't collect anything between 2017-11-25 and 2017-11-26:
- Timestamp: 2017-11-26T22:20:17.672
- Function App version (1.0 or 2.0-beta): 1.0.11388.0 
- Function name(s) (as appropriate): NotifyFromQueue
- Invocation ID: d3a02834-317f-49ef-9f6b-560182e91354
- Region: West Eu

Please let me know if you need anything else to investigate this issue

**Comment by christopheranderson** [comment]
Sorry we missed this over the holidays. I'm going to close this since we don't have the data anymore to investigate this. If it is reproing, please open a new bug. In the future, if its a critical service bug, you can also use the support ticket system in the Azure portal which has an SLA. (whereas GitHub is best effort)
