### ISSUE TITLE
API Definition with Swagger

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#292]
Hello everybody, 

how does configuration of API metadata work? I've saved the link to my public Swagger definition in the portal. Is it now automatically providing a swagger-ui web page somewhere? I haven't been able to find it through the standard links such as myazurefunctions.azurewebsites.net/swagger
I'm running my functions on the dynamic pricing tier, don't know if that matters. Thanks! 

Best regards
--Oliver.

**Comment by mathewc** [comment]
There is no swagger support currently in Azure Functions.

**Comment by christopheranderson** [comment]
Assigning to Matthew to start investigation.

**Comment by johnnliu** [comment]
OK.  We need this to come back from the backlog.

Flow, Logic Apps, PowerApps, Cognitive Services all work really well with a Swagger definition file.  In Satya's Australian developer keynote Swagger is explicitly called out in the developer session right after - as the magic glue that links the different products.

Wishlist:

My ideal scenario is that when you already have a HTTP trigger function, AzureFunction should be able to generate the JSON for you.

If you use Request Body with additional JSON input - then the parameter in: type "Body" should be set as well (or at least there should be examples of this).

The JSON file should be hostable from AzureFunction - there are several examples that tells us to spin up a separate API App just to host the JSON file, which I think it's counter to the Severless motto.

If there's integration with swagger.io editor - then the code needs to add swagger.io as allowed in CORS as well.  Otherwise, we should be able to run and test the swagger directly in AF.

@Alexkarcher-msft - Hello!  IIRC you are the Swagger guy.  Pizza helps my memory :-)

**Comment by mattchenderson** [comment]
@johnnliu Thanks for the post. We are working on this, but the plan isn't final so it hasn't been assigned a milestone. I'll bump it up to Next so that it doesn't look abandoned. 😃 

Would you be able to point to the examples using API Apps to host? That is not a desirable approach, although I suppose it does make for a quick workaround. It is possible to host a Swagger doc from a function app, but it isn't the easiest thing right now.

**Comment by johnnliu** [comment]
Links I found last week:

https://docs.microsoft.com/en-us/azure/connectors/connectors-native-http-swagger - "blob storage"

https://blogs.msdn.microsoft.com/logicapps/2016/07/31/creating-codeless-swagger-connectors-for-logic-apps/ - use swagger.io and YAML (I'd rather kill myself).  Then host in blob again.

https://blogs.msdn.microsoft.com/martinkearn/2015/05/22/get-started-with-azure-logic-apps-and-your-own-api-app-in-5-minutes/  - this is about logic apps and swagger and API APP.

**Comment by johnnliu** [comment]
This is probably the most active/current article.

https://blogs.msdn.microsoft.com/carlosag/2016/05/09/using-azure-functions-in-powerapps/ - and it doesn't talk about how to host the Swagger json file.

Additionally, I find it lacking parts on how to define the Request.Body (json args) as I think most people will use that over query string.

I also REALLY would like the authentication part to be generated automatically.  E.g.  if I use AAD auth for my AF, the swagger file should say so, and in Flow it should automatically offer the way to authenticate with AAD account from Flow.   - in fact I think this is a critical feature request.

**Comment by yvele** [comment]
But what about that in Azure Function Portal? How is this helpful? I don't understand this "feature":

![image](https://cloud.githubusercontent.com/assets/4225430/20516914/1a621abe-b099-11e6-8e92-0dbb04d981e8.png)

![image](https://cloud.githubusercontent.com/assets/4225430/20516981/3aa6cbb2-b099-11e6-9f84-6dae03e735cd.png)

**Comment by johnnliu** [comment]
Hi @yvele that's what I mean - Functions give a place to put the swagger definition file, but you need to spin up some other web site to host the json file.  I think Functions should serve the file too.  I can't find good guidance on where to create the file.

**Comment by xpouyat** [comment]
Some good info here: http://anthonychu.ca/post/restful-apis-swagger-openapi-azure-functions/

**Comment by johnnliu** [comment]
I kind of think it's brilliant and sad at the same time that we need to write a second function to return the json file for the first function ;-)

Starting to think it might be cheaper to use Azure Blob Storage and CDN cache link for just one file, depending on how often various services hit the endpoint to grab the json file.

**Comment by bootsector** [comment]
Sorry to jump in with a question, but why using Functions instead of, for example, Azure API App? I have been working with API Apps for quite some time and it supports everything an Industry Standard PaS for webservices should support.

From my understanding, Azure Functions is part of WebJobs which is meant for running jobs, giving you an additional option to get a job triggered via a HTTP request and running a "function", in the Cloud.

Is there something I'm missing or should I start migrating all my webservices from Azure API App to Azure Functions (whenever it supports Swagger, at least, of course)?

**Comment by wobba** [comment]
I wrote a function which dynamically generates a working Swagger def for PowerApps/Flow - http://www.techmikael.com/2017/08/maybe-most-useful-azure-function-ever.html

**Comment by alexkarcher-msft** [comment]
This has been delivered: https://docs.microsoft.com/en-us/azure/azure-functions/functions-openapi-definition 
Please create or thumb up more detailed work items, such as full definition generation.

thanks for all the feedback!

**Comment by wobba** [comment]
@alexkarcher-msft Ok, so we close this one, and create a new issue asking to get a usable swagger definition..no problem :) Then again, I have working code to go from C# to a usable Swagger definition, much like Swashbuckle.

**Comment by alexkarcher-msft** [comment]
Yep, we already have a work item for a usable/complete definition :)
https://github.com/Azure/azure-webjobs-sdk-script/issues/1510

Good work on that blog post as well!

**Comment by johnnliu** [comment]
both #292 and #1510 looks closed.  Still no happy path.

In LogicApps/Flow if we use HTTP Trigger and use "parse JSON" it will generate the OpenAPI schema needed to call that LogicApps trigger.  Can we get the same in AzureFunctions?
