### ISSUE TITLE
Can't trigger on $logs blob container 

### ISSUE THREAD

**Issue by LoungeFlyZ** [Azure/azure-webjobs-sdk-script#300]
I want to process my storage logs as they are created using a function.  However i get the following error message when setting up the trigger to point at $logs container:

`Invalid container name: $logs.`

The horrible workaround is to use a timer to periodically check the logs, but this is complex and error prone and you need to keep track of what files you have synced already. 

It would be much nicer to have a function trigger whenever a new log file blob is created in $logs.

I wrote up a bit about my trails with this here: http://www.looselytyped.net/2016/04/24/parsing-azure-blob-storage-logs-using-azure-functions/

**Comment by mathewc** [comment]
Yeah, this is actually a limitation of the WebJobs SDK that this repo builds on. [BlobTriggerAttribute](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs/BlobTriggerAttribute.cs#L41) does validation on blob paths and rejects $logs (because generally you can't use special characters in these names).

**Comment by LoungeFlyZ** [comment]
Understood.  Would you like me to open an issue there? or is that not needed since i think you work in that repo also?  Thanks for the help BTW.

**Comment by mattchenderson** [comment]
@mathewc Should we just refile this in the SDK repo?

**Comment by christopheranderson** [comment]
Move to the sdk repo to properly track this issue - https://github.com/Azure/azure-webjobs-sdk/issues/715
