### ISSUE TITLE
Nuget Restore Improvements

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#312]
Currently we only run nuget restore for a C# function when the host is up and running and we see a change to project.json. We also need to support scenarios where the project.json is modified (or created) when the host is NOT running. When the host starts, we should be able to discover these modifications and run restore.

We can use an approach like David suggested:

"Yes, we will find a way to make this work when deploying via Kudu API. Fabio, I think we could just keep track of the timestamp of project.json (under somewhere data folder). When host starts, any time we see the current timestamp is different from what we saved, we should run nuget."

**Comment by mathewc** [comment]
It'd be good if the implementation of this could be generalized so it would also allow us to do the same for Node NPM when we enable that.

Perhaps we write a single timestamp somewhere capturing the last time the host has successfully started. Then the various language invokers can check this on startup, compare with project.json / package.json timestamp and run as needed. That will allow them to easily discover file changes that have occurred while the host was sleeping.

**Comment by fabiocav** [comment]
Bringing the comment from an internal email thread to the issue; for NuGet, instead of keeping track of the timestamp and restoring based on that, since we really only rely on the lock file that results from a package restore, we can identify the need to perform a restore if the following conditions are true:

- We have a `project.json` file, but no `project.lock.json`
- We have a `project.json` file and a `project.lock.json` but the lock file is outdated or doesn't match the project.json

**Comment by davidebbo** [comment]
Also, we need to make sure we don't do it simultaneously from multiple instances, which could cause corruption.

**Comment by mathewc** [comment]
Yes, the multi-instance issue has come up in the context of function logs as well https://github.com/Azure/azure-webjobs-sdk-script/issues/164. The same mechanism of identifying a "primary" instance for things like recompilation logging, nuget restore, etc. will be needed.

**Comment by rarayudu** [comment]
Can we also support nuget resolution every time the host comes up to fetch the newer version packages if any?

It will be useful in case of bug fixes instead of asking customers to upgrade every time we roll out a fix/update. If the customer don't want that he can just turn off auto updates (with a flag).

**Comment by christopheranderson** [comment]
Seems related to https://github.com/Azure/azure-webjobs-sdk-script/issues/254 which I'd like to consider for rc:should-have
