### ISSUE TITLE
Feature Planning: Slack webhook

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk-script#318]
Currently, there's no way to configure slack token as described in [this SO question](http://stackoverflow.com/questions/36949872/configure-slack-authentication-token/36950704).

**Comment by christopheranderson** [comment]
I want to reevaluate this soon.

**Comment by christopheranderson** [comment]
I believe the only issue here is that the portal doesn't easily allow us to set a key. I'll test this and create a Portal UX issue to track. Keeping this open just in case there are additional issues that pop up.

**Comment by christopheranderson** [comment]
Steps to test slack token
1. Create Generic WebHook (I used Node) and have the sample just log data
2. via scm site, go to ./data/Functions/secrets/{function}.json
3. replace that token with the Slack provided token
4. Trigger WebHook and watch the log

So there are two issues before we can light up proper support for Slack in Functions.
1. Parsing www-form-urlencoded bodies into objects - https://github.com/Azure/azure-webjobs-sdk-script/issues/317
2. Portal UX allowing for 2 way key management - https://github.com/projectkudu/AzureFunctionsPortal/issues/360

Once those two have lit up, we can add it back to the bindings.json - https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Bindings/bindings.json

So that said, this is going to become a feature planning issue, and I'm going to triage it to next considering that is where its dependencies are triaged.

**Comment by christopheranderson** [comment]
I'd like to include this in "should-have" since I hope it's relatively low hanging fruit which results in big user impact. It's basically a bug of an existing feature.

**Comment by davidebbo** [comment]
Maybe we need a way to tag such 'should have' in GitHub issues?

**Comment by christopheranderson** [comment]
I have one `rc:should-have`. I just thought I should discuss it first. :)

**Comment by christopheranderson** [comment]
Will be addressed by this: https://github.com/projectkudu/AzureFunctionsPortal/issues/360

**Comment by christopheranderson** [comment]
This is done now! :)
