### ISSUE TITLE
.deployment file with Node Functions does not trigger script

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#324]
Hello--, 

I've tried to automatically install Node dependencies (as specified in package.json) whenever there is a new push to a Git repository.
According to https://github.com/projectkudu/kudu/wiki/Customizing-deployments this should be possible by creating a `.deployments` file in the root folder that triggers the according command (`npm install`).

So my .deployment file looks like that (also tried without `project = .`):
```
[config]
command = deploy.cmd
project = .
```

My deploy.cmd looks like that:
```
cd lib
call npm install
```

If invoked manually through the console installation of node dependencies work. However, the script does not seem to be triggered automatically when a new version is deployed. Is there anything I'm missing? Thanks!

Best regards
--Oliver.

**Comment by davidebbo** [comment]
That's strange. So if you put a simple `echo` statement in your script, you don't see it at all in the deployment output logs? Can you share a test repo that has this behavior so we can investigate? Thanks.

**Comment by arafato** [comment]
I'm currently deploying from OneDrive.
Here's the deployment output logs:
Running deployment command...
```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling Basic Web Site deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Finished successfully.
```
Generating deployment script...
`Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --basic --sitePath "D:\home\site\repository"')`

**Comment by arafato** [comment]
Just tried it with Github as deployment source (https://github.com/arafato/azurefunc-deploy-test).
Same output as above.

**Comment by davidebbo** [comment]
I tried and your script is definitely getting called. The problem is indeed that it runs from the repository folder and not the wwwroot folder. If you want the repo to be directly in wwwroot so you  avoid file copying, try the following:

- First disconnect from source control in the Azure portal
- In the Azure Portal App Settings, set `SCM_REPOSITORY_PATH=wwwroot`, per [this page](https://github.com/projectkudu/kudu/wiki/Deploying-inplace-and-without-repository#inplace-deployment).
- Now push your repo again and you script will run from wwwroot (because your repo will be right there).
