### ISSUE TITLE
PowerShell - errors not handled

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-webjobs-sdk-script#371]
If I add a terminating error to my PowerShell script (`write-error "snakkes -erroraction Stop`) there is no indication of the error in the console/logs, and the function still reports "Success" (although script execution seems to halt). We need a much better visibility into the actual health of the script, and all streams (output/warning/verbose/error) before PowerShell in Functions in really useable.

**Comment by mathewc** [comment]
Thanks. We're revamping our PowerShell support as we speak (see PR [here](https://github.com/Azure/azure-webjobs-sdk-script/pull/357)). In addition to adding custom module support and other features, hopefully that work will address these issues as well.

Feel free to check out that PR and comment on it.

**Comment by mathewc** [comment]
@tohling Do your PowerShell changes address this issue?

**Comment by tohling** [comment]
Yes, with the next release, if the customer's script executes the following

Write-Error "Test error message!" -ErrorAction Stop

the customer should see 2 trace messages in the logs:

1. "Function completed (Failure, Id=<some ID>"
2. "Exception while executing function: Functions.<functionName>. System.Management.Automation: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Test error message!." 

Sample output in logs is shown below:

```
2016-06-02T15:17:34.512 Function started (Id=26fa7834-5cfb-4407-ac06-ea2acfccff29)
2016-06-02T15:17:35.198 Function completed (Failure, Id=26fa7834-5cfb-4407-ac06-ea2acfccff29)
2016-06-02T15:17:35.232 Exception while executing function: Functions.HttpTrigger-Powershell-Modules. System.Management.Automation: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Test error message!.
```

**Comment by mathewc** [comment]
Closing this based on Ling's comments above. The next imminent release will include these changes.
