### ISSUE TITLE
Externalize blob trigger failure retry config

### ISSUE THREAD

**Issue by laurence-hudson-tessella** [Azure/azure-webjobs-sdk-script#468]
There appears to be some undocumented functionality wherein a failing Blob triggered (node only?) azure-function makes 4 retry attempts (5 total attempts). Can we allow this number be specified (or disabled) in function.json?

**Comment by mathewc** [comment]
Yes, since Azure Functions is build on the WebJobs SDK, existing documentation on poison blob handling can be found in the WebJobs SDK doc. We're still catching up on Functions doc as you can see. E.g., [here's the page](https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-webjobs-sdk-storage-blobs-how-to/) on blob processing that mentions how the `MaxDequeueCount` can be configured.

You can already control this via host.json settings. See the mention of `maxDequeueCount` on [this](https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json) wiki page.
