### ISSUE TITLE
Feature Planning: first class F# support

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#499]
This is a tracking item for first class F# support. We'll be tracking the requirements and issues for first class F# support via this item. Feel free to leave comments about features/design patterns. 

See Don's post below for more details

**Comment by enricosada** [comment]
My feedback:

**good**: f# function, not methods. `async` (the f# expr) also, not only `Task`.
**ideal**: having a Type provider over `function.json`, so the main is type generated and type safe. It also help about discoverability of parameters, because the `Run` function atm doesnt have an interface (afaik).

for example for the [ResizeImage sample](https://github.com/Azure/azure-webjobs-sdk-script/tree/dev/sample/ResizeImage) something like:

```
let resizeIt original resized = async {
    let resizeToSmall = myResizeImpl 200<px> 300<px>
    do! original |> resizeToSmall resized 
}

type Resizer = AzureFunction<"../function.json">
let azure = { Resizer.RunAsync = resizeIt }
```

**Comment by dsyme** [comment]
Hi @christopheranderson  @fabiocav , here is my take on a first-cut of the feature specification.  Please edit into the top of this issue?

### Status

Design questions:

-[ ] ``#load`` directives in F# functions? 
-[ ] Use a more idiomatic F# signature, e.g. tuple returns?
-[ ] Nuget package references?

Core Implementation

-[ ] Allow debugging to be turned off. In code: ``TODO: Get debug flag from context. Set to true for now.``
-[ ] Turn off optimization when debugging is on
-[ ] Get nuget package references working
-[ ] Get CI passing for ``fsharp`` branch

Core QA

-[ ] Check a range of failure conditions, especially ones that are "catastrophic" to compilation: Bad DLL references, Bad nuget package references, Bad ``#load`` references, Basic type error, Basic runtime error
-[ ] Check the off-by one conditions for diagnostic error reporting, especially when mapping from
FSharp.Compiler.Service line/column to the Azure Functions diagnostics
-[ ] Check ``FSharpEndToEndTests`` against C# equivalents and make sure everything is being tested.
-[ ] Check F# tests are being run as part of CI.  e.g. [this log](https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script/build/1.0.14-dxmibwcr/tests) shows no FSharp tests, though some CSharp tests

-[ ] Double check F# type providers (FSharp.Data) can be used
-[ ] Double check what happens with exceptions at runtime
-[ ] Double check implicity referenced DLLs are the same as C#
-[ ] Double check symbols are being generated correctly and debugging works.  Code seems to indicate they are.
-[ ] Double check "hot runtime" for F#. Should be identical to C#.

TODO: Delivery 

-[ ] Add basic F# docs to website
-[ ] Add basic F# samples to user-visible samples collection
-[ ] Write blog post announcement with samples



### Function format

Here is a sample function:

```fsharp
open System
open Microsoft.Azure.WebJobs.Host

let Run (input: string, output: byref<string>, log: TraceWriter) =
    log.Verbose(sprintf "F# ApiHub trigger function processed a file...");

    output <- input
```

Functions are authored as ``.fsx`` files.  This is done on the assumption that functions are often small, script-like pieces of code and can benefit from the "implicit project" of a script through ``#r`` and ``#load`` references.  

### Function Signatures

Functions follow the C# signature exactly.

* Functions currently report outputs through the use of byref parameters.

* The names of the parameters must match those in the config.

* The optional logging parameter is automagically inserted by the Azure Functions host.

Question: do we want to use a more idiomatic F# signature, e.g. tuple returns.  However tuple returns are problematic because names are not avaiable for the different fields and positions would need to be used.

Question: could we allow different signatures in later versions?  What's the upgrade story?


### DLL, Nuget and File References

Functions are loaded and executed with an implicit set of DLL references.

The set of implicit DLL references is the same as C#.

> Question: does it make sense to use ``#load`` directives in F# functions?  What is the set of current source code files (i.e. current directory) that we would have access to?  Presumably from function-author perspective this would be the current directory of the script within the GitHub or other source control tree. 

### Editing Functions


Because functions are scripts, they are usually edited in a tool like Visual Studio or Visual Studio Code, which provides editing support for F# scripts.  However that tool doesn't know the set of implicit references being used by Azure Functions.  For this reason it is useful for the function author to add a declaration like the following to ensure the DLL references are active when using the function:

```fsharp
//----------------------------------------------------------------------------------------
// This prelude allows scripts to be edited in Visual Studio or another F# editing environment 

#if !COMPILED
#I "../../bin/Binaries/WebJobs.Script.Host"
#r "Microsoft.Azure.WebJobs.Host.dll"
#endif
```

This prelude is optional but is included in the test cases that form part of this PR.


### Data Type formats

As for C#

### Version & Package management

Default references are the same as for C#.

> Quesiton: are nuget package references allowed in F# code and are they resoved correctly.

### Testing/CI

In progress.  Testing should be 1:1 with C# testing for all function definitions.

> TODO: Check ``FSharpEndToEndTests`` against C# equivalents and make sure everything is being tested.

F# tests should be run as part of CI.


### Remote debugging

As for C#.  

> TODO: check that symbols are being generated correctly.

> TODO: resolve this ``TODO: Get debug flag from context. Set to true for now.``


### Local debugging

As for C#

### Hot runtime

As for C#.

### Compilation

The FSharp.Compiler.Service component is used for compilation

### List of samples in https://github.com/Azure/azure-webjobs-sdk-script/ repo

* Each C# sample should be matched by an F# sample, e.g. ``sample/DocumentDB-FSharp/...``

Maintaining this list of samples and keeping the code up-to-date is a significant ongoing cost.

### FSharp.Core compile-time reference and runtime dependency

``WebJobs.Script.Host`` and ``WebJobs.Script`` already include FSharp.Core as a runtime component.
These should use ``FSharp.Core 4.4.0.0`` at runtime and compile-time.  

FSharp.Core is a binary-comatible component and later releases of Azure Functions can move to using a
later version of FSharp.Core at runtime.

There is currently no way to specify the required .NET Framework or specific version of FSharp.Core
as part of the F# ``.fsx`` scripting model.

All compilation and compile-time execution of F# Type Providers operate with the following binding redirect active:

    <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0" />

> Question: what about binding redirects for imported packages?


### Compilation Diagnostics

Compilation diagnostics returned by FSharp.Compiler.Service are reported as Azure Functions diagnostics.

Correct compilation diagnostics should be given for a range of failure conditions, especially ones that are "catastrophic" to compilation:

* Bad DLL references
* Bad nuget package references
* Bad ``#load`` references
* Basic type checking errors
* Runtime exceptions

### F# Type Providers

F# Type Providers execute at the time of script compilation. The compilation happens in the script host.
This operates with the same rights and priveleges as script execution.

**Comment by tpetricek** [comment]
Regarding the `debug` flag - it seems that the C# compilation process always uses debug mode, just like the current F# prototype. The call to `GetScriptCompilation` [here in the source code - in master](https://github.com/Azure/azure-webjobs-sdk-script/blob/master/src/WebJobs.Script/Description/DotNet/CSharp/CSharpCompilationService.cs#L45) always sets the second parameter `debug` to `true`.

**Comment by fabiocav** [comment]
@tpetricek that is correct. We have discussed introducing a configuration that to drive that logic (e.g. when users had the portal open, remote debugging or set explicitly), but that work hasn't been prioritized, so it should be safe to just continue to compile in `debug` mode for the time being.

**Comment by dsyme** [comment]
@fabiocav @christopheranderson Could you update this thread with links about where we should submit draft documentation and website updates to complete the items in the "Delivery" section?  When we met in Redmond you showed me the various sites to submit to (I think one site was internal to MS), but I don't think I kept a record of them

**Comment by dsyme** [comment]
Ping @fabiocav @christopheranderson :)

> Could you update this thread with links about where we should submit draft documentation and website updates to complete the items in the "Delivery" section please? 
> When we met in Redmond you showed me the various sites to submit to (I think one site was internal to MS), but I don't think I kept a record of them

Thanks!
Don

**Comment by christopheranderson** [comment]
Documentation can be submitted to: 
 - https://github.com/Azure/azure-content/tree/master/articles/azure-functions

Specifically, we'll need a `functions-reference-fsharp.md` doc, maybe some touch ups.

Summoning @ggailey777, who might know other docs that would need updating.

If we want to update any marketing material, it just needs to be enumerated as an issue to our Portal repo. Specifically, we probably want our front page talking about F# and linking to samples.

**Comment by mathewc** [comment]
FYI: @fabiocav has merged all of this to dev, and it will go out with the next release :)

**Comment by fabiocav** [comment]
Updated the existing F# templates to work with the new model here: https://github.com/Azure/azure-webjobs-sdk-templates/pull/291

Need to work on additional templates covering additional scenarios and bindings.

**Comment by lindydonna** [comment]
@dsyme We're tentatively targeting Thursday for lighting this up in the Azure portal, and Chris will write a blog post that describes what's new. We should have some docs that go out with this as well, something similar to https://github.com/Azure/azure-content/blob/master/articles/azure-functions/functions-reference-csharp.md. Rendered version: https://azure.microsoft.com/en-us/documentation/articles/functions-reference-csharp/
