### ISSUE TITLE
Javascript Parameter Ordering

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#50]
e.g. `function (workItem, context)` should become `function (context, workItem).`

**Comment by christopheranderson** [comment]
This is correct, but should be part of a larger effort at cleaning up the JavaScript experience.

Ideally, we have JavaScript working where all the inputs are included on the function call:

```
module.exports = function(context, trigger, ...inputs)
{
    context.log("I have ${inputs.length} inputs");
    context.done();
}
```

We also need to add support for multiple outputs, but I think that we can discuss that, first in an offline conversation.

**Comment by mathewc** [comment]
That implies a strictly positional ordering, since we don't know the declared order in code. If they add or remove parameters, their function definition changes. Whereas with what we now the function definition never changes. There's some purity to that.

What is the motivation/benefit of making this proposed change? I don't see it being better than what we have now where bindings are accessed off of context.

**Comment by davidebbo** [comment]
I think it's a cleaner usage pattern to receive an object directly instead of having to dig it out of a context. One key scenario that I really want to look good is WebHooks. In that case, we receive one JSON blob which becomes the one and only 'data' parameter. If I have to dig something out of the context, how do I even know what it's called? I'd need much deeper knowledge about the concept of named bindings, ...

And if there are more than one, the ordering is simply what's listed in the bindings.

'Purity' is a nice thing until it start coming in the way of a simple user model in the common cases.
