### ISSUE TITLE
Support / Remove PowerShell *-job cmdlets

### ISSUE THREAD

**Issue by theMichaelB** [Azure/azure-webjobs-sdk-script#537]
Currently it seems possible to submit a job via `Start-Job` but that job cannot be received with either `Get-Job` or `Receive-Job` The result either being that the cmdlet hangs for five minutes, or it silently fails (without getting the job) 

After some persuasion the following error can be found

>  get-job : Access to the path 'Microsoft\Windows\PowerShell\ScheduledJobs' is denied. 

Are Jobs likely to be supported in future? if not, can the relevant cmdlets be removed.

**Comment by tohling** [comment]
Assuming that you are using Azure Functions release version ~0.3 or greater, these cmdlets should work.

**Start-Job** returns a _System.Management.Automation.PSRemotingJob_.  If you want your Function's log to have similar output as the one you see in a typical PowerShell console, you can pipe the _PSRemotingJob_ object to Out-String.

Here is a sample _HttpTrigger_ type Function that uses **Start-Job**, **Get-Job** and **Receive-Job** to execute a background job that retrives the list of existing w3wp process information.

```
$json = Get-Content $triggerInput -Raw | ConvertFrom-Json
if ($req_query_name) 
{
	$message = "Hello $req_query_name";
}
else
{
	$message = "Please pass a name on the query string";
}

Start-Job -Name "Getw3wp" -ScriptBlock {Start-Sleep -s 10; Get-Process | Where-Object {$_.Name -eq "w3wp"};} | Out-String;

while (($job = Get-Job -Name "Getw3wp") -and ($job.State -eq 'Running'))
{
    Write-Output "Job status: Running";
    Start-Sleep -s 2;
}

Write-Output "Job status: Completed";
Receive-Job -Job $job | Out-String;
Out-File -Encoding Ascii $res -inputObject $message;
```

The logfile for this Function when triggered is as follows.  Note that due to the timestamp prefix on a log entry, the output's first line is not aligned with the rest of the output.  

```
2016-08-01T06:20:49.215 Function started (Id=e710d92f-7328-4ef2-8598-86e943d6a0dc)
2016-08-01T06:20:50.935 Id     Name            PSJobTypeName   State         HasMoreData     Location   
--     ----            -------------   -----         -----------     --------   
1      Getw3wp         BackgroundJob   Running       True            localhost
2016-08-01T06:20:50.950 Job status: Running
2016-08-01T06:20:53.013 Job status: Running
2016-08-01T06:20:55.025 Job status: Running
2016-08-01T06:20:57.036 Job status: Running
2016-08-01T06:20:59.049 Job status: Running
2016-08-01T06:21:01.058 Job status: Running
2016-08-01T06:21:03.060 Job status: Running
2016-08-01T06:21:05.061 Job status: Running
2016-08-01T06:21:07.063 Job status: Running
2016-08-01T06:21:09.070 Job status: Running
2016-08-01T06:21:11.082 Job status: Completed
2016-08-01T06:21:11.129 Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id ProcessName           
-------  ------    -----      ----- -----   ------     -- -----------           
    407      34    30052      28352   559             588 w3wp                  
    863      91    56356      36412   363     6.42   5520 w3wp                  
   1131     135   100052       8348   444     7.23   5996 w3wp
2016-08-01T06:21:11.145 Function completed (Success, Id=e710d92f-7328-4ef2-8598-86e943d6a0dc)
```

**Comment by theMichaelB** [comment]
Running the same scripts this morning and everything appears to be running as expected! Thank you for the reply.
