### ISSUE TITLE
CLI: would be nice to have a custom icon for the server console

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#595]
Currently, it looks like this on my taskbar, which makes it hard to know what it is:

![image](https://cloud.githubusercontent.com/assets/556238/17826772/ff7d2c9e-6628-11e6-9bb5-ad3ed6028dfb.png)

Would be nice to have some custom Functions icon there.

**Comment by fabiocav** [comment]
We also need something like this :)
```
                                        
                                        
                                        
                 ++++++++++             
                ++++++++++              
                +++++++++               
            =  +++++++++  =             
          ==   +++++++=   ===           
        ===   ++++++++      ==          
       ==     ++++++++++++++ ~==        
     ===     +++++++++++++     ===      
   ===      +++++++++++++        ==     
   ==       ======++++++          ==    
    ===           +++++         ==      
      ==         ~++++        ===       
        ==       ++++        ==         
         ===    ++++       ==~          
           ==   ++        ==            
               ++                       
               +                        
              +                         
                                 ______                _   _                 
     /\                         |  ____|              | | (_)                
    /  \    _____   _ _ __ ___  | |__ _   _ _ __   ___| |_ _  ___  _ __  ___ 
   / /\ \  |_  / | | | '__/ _ \ |  __| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
  / ____ \  / /| |_| | | |  __/ | |  | |_| | | | | (__| |_| | (_) | | | \__ \
 /_/    \_\/___|\__,_|_|  \___| |_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
                                        
```

**Comment by christopheranderson** [comment]
Tell me size/format and I can get the resource to you

**Comment by lindydonna** [comment]
Should run host in a separate window (in which case the icon should be used)

**Comment by lindydonna** [comment]
```
                  %%%%%%   
                 %%%%%%             
            @   %%%%%%    @          
          @@   %%%%%%      @@            
       @@@    %%%%%%%%%%%    @@@        
     @@      %%%%%%%%%%        @@      
       @@         %%%%       @@        
         @@      %%%       @@          
           @@    %%      @@            
                %%                     
                %   
```

**Comment by lindydonna** [comment]
Extra credit: add colors: 
![image](https://cloud.githubusercontent.com/assets/4260261/21407019/68c71ea6-c783-11e6-9ddc-ca52dc36b87d.png)

**Comment by ahmelsayed** [comment]
Here is what it looks like now. 
![image](https://cloud.githubusercontent.com/assets/645740/21569632/748a8074-ce73-11e6-9f29-e00f1b7e32a6.png)

note that to get David's original ask, which is to have an icon in the taskbar, this would require more work.

AFAIK, console applications  can't have their own icons in the taskbar because they don't have UI. The console UI you get is from conhost.exe not func.exe, so that would require to change the icon for conhost.exe which is shared with all the console applications. 

What we can do however is run as a WinForm or a WPF app, i.e a `csc /target:winexe` vs `csc /target:exe` and then we will get control over the icon, but we lose the console interface.
The experiment I have working is to launch as a winexe, then launch again as a console app, then set the winexe window to be the [parent](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633541(v=vs.85).aspx) of the console window, which will display it inside the winexe frame. It sounds complicated, but what I meant to say is that it's possible but not straight forward with a bunch of a very Windows specific code. Let me know if you want me to get that in.

**Comment by davidebbo** [comment]
If it's a significant pain/investment, it's probably not worth doing...

**Comment by lindydonna** [comment]
I agree with David. It would be nice to have but not critical. For Visual Studio, we may even pipe the output to the VS Output window, in which case there may not even be a separate console window.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-cli#11
