### ISSUE TITLE
F# Compiler depends on MSBuild12 (VS2013)

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#600]
This is an unexpected runtime dependency, and requires that you've installed the build tools for VS 2013.

@dsyme, @tpetricek Is there a way for that dependency to be removed?

**Comment by dsyme** [comment]
I can prioritize looking at this on Tuesday (Monday is a holiday here).  Is that ok?

**Comment by mathewc** [comment]
Sounds good, thanks :)

**Comment by mathewc** [comment]
One other thing: I've noticed that the F# compiler has about an 11 second startup time the first time an F# function is compiled in an app domain. Subsequent compilations in the same app domain don't pay that cost.

Is there a knob or something we can configure to reduce this, or is it a set cost? For our Samples app which I run very often for testing etc., I've disabled the F# samples to avoid this 10 second hit, since I run this very often (they're still there and can be enabled when we want to run them).

**Comment by dsyme** [comment]
@mathewc This is the cost of JIT-compiling the F# compiler codebase itself.  On a usual machine it is 3-5 seconds.  

I think the only way to  remove that cost in a new appdomain is to use a [domain neutral assembly](http://stackoverflow.com/questions/3058110/what-are-the-steps-for-making-domain-neutral-assemblies)

**Comment by dsyme** [comment]
@mathewc Back on the original question - can I ask which dependencies are suitable?  Specifically

* Is a dependency on MSBuild 14 suitable?
* Is any dependency on an MSBuild version possible?

The problem is that the F# compiler can in some circumstances call MSBuild assembly resolution for ``#r`` references.  This dependency/capability has been a huge recurring problem for FSharp.Compiler.Service on both .NET Framework and (especially) .NET Core.  To be honest we'd like to completely remove the dependency for usage scenarios like Azure Functions.

**Comment by dsyme** [comment]
@mathewc Any ideas on these questions on alowable MSBuild API dependencies? https://github.com/Azure/azure-webjobs-sdk-script/issues/600#issuecomment-244321696

**Comment by mathewc** [comment]
Well, on the Azure VMs that Functions runs on, both MSBuild 12 and 14 are installed. This is really about making sure things work for local development - people likely have MSBuild 14 on their local boxes but not 12, if they're using the latest VS. So yes, 14 is better than 12 - to get things to work for me locally, I had to go install an old version of MSBuild. We don't want people to have to do that.

I agree with you that removing the dependency all together might be best, in the spirit of minimizing dependencies, but I don't know if that is possible for you.
