### ISSUE TITLE
Log message: "Host lock lease renewed"

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#611]
I'm running the latest version (v1.0.0-beta1-10355) of the scripthost sdk on my Azure Website instance and I'm seeing the following message every 30 seconds or so:

`Host lock lease renewed`

Is there something I need to update or is this a non-issue?

Thanks!

**Comment by fabiocav** [comment]
That's a normal message to trace host lock acquisition activity. This message should only be logged if your trace level is set to verbose, so if that's the case, nothing to worry about.

**Comment by jamesdixon** [comment]
Thanks for the quick reply, @fabiocav!

This may seem trivial, but where would I verify my logging level? Can't remember explicitly setting it.

**Comment by fabiocav** [comment]
Trace verbosity is typically configured in your host.json file as documented here: https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json

Trace level would also be set to verbose if you're running in development mode (bringing this up since you're consuming the SDK yourself)

**Comment by jamesdixon** [comment]
Interesting. The only thing I have set in `host.json` is the `id` parameter.

As for being in development mode, this isn't running locally if that's what you're referring to. For what it's worth, I'm fairly certain that I never saw this until upgrading to v1.0.0-beta1-10355.

All that said, it doesn't seem to be causing an issue, so not a high priority 👍

**Comment by fabiocav** [comment]
Development mode may be enabled in code or with an app setting, but that is something you'd have to set explicitly, so I'm assuming that wasn't the case.

The primary host logic (which depends on lease mentioned above) was introduced in the last release, that's why you haven't seen it before.

As mentioned, this should only be logged when in verbose mode, but the activity is normal. I'll investigate to make sure we don't have an issue with the trace verbosity level somewhere.

**Comment by jamesdixon** [comment]
Thanks for the explanation, @fabiocav. Really appreciate your help!

**Comment by fabiocav** [comment]
@jamesdixon, This doesn't repro in the Azure Functions environment, but I have a good idea of what is going on, but to validate, can you share a snippet of code showing how you're currently initializing and running the host?

**Comment by jamesdixon** [comment]
@fabiocav I'm basically deploying via option 2 seen here: https://github.com/Azure/azure-webjobs-sdk-script/wiki#option-2-no-http-functionwebhook-support

Here's a screenshot that shows my directory layout:

![image](https://cloud.githubusercontent.com/assets/110114/18021880/b051fc10-6ba7-11e6-9b1d-ff439984e2b5.png)

The `host.json` file contains a single property, `id` with a random GUID.

The `run.cmd` file calls the following command: `.\bin\Microsoft.Azure.WebJobs.Script.Host.exe
`
And last but not least, the `bin` directory contains the Functions SDK.

Let me know if there's anything else you'd need.

Cheers.

**Comment by fabiocav** [comment]
That makes sense, and is caused by what I suspected. The host executable uses a console logger that is currently ignoring the trace level. I'll flag this issue as a bug so we can have this addressed. This may not be prioritized high enough to go in the next couple of milestones, but since this would be a small change, so I'll try to see if we can squeeze it in.

**Comment by jamesdixon** [comment]
Thanks for confirming. And yeah, no worries on making it a priority. I just wanted to be sure that there was nothing fishy going on that might cause problems.

Again, appreciate your help!
