### ISSUE TITLE
Function app not allowing 2 consecutive dashes & Upper case letter in a valid EventHub name

### ISSUE THREAD

**Issue by JatinBavishi** [Azure/azure-webjobs-sdk-script#625]
The function url: https://westeuropeiothubdiagnostics.scm.azurewebsites.net/api/functions/iotfgwwesteuropediagnostics

Repro steps: 
Create an Azure function with a trigger on this event hub endpoint to see this error. 

Expected: This being a valid event hub endpoint Azure functions should be able to listen for messages in this event hub endpoint. 

Try listening on the same end point using the service bus explorer tool copied in the same UNC path. It works as expected. 

Event hub connection string and name is shared in file attachment: reprofiles.zip
Event Hub name having consecutive dashes & upper case letter : azthingsiotfgwwesteurope--operationMonitoring

IoTHub product team was engaged. Feedback received was that Azure function has following deficiencies. Event Hub name is fine. The Azure Functions portal also prohibits upper case event hub names, which is wrong.

Status: Customer can bypass this error by following the guidelines in this error message (which seems quite clear cut) and this appears a By-Design behavior. But they say that valid event hub endpoints may have consecutive dashes & Uppercase letters in the names & this should be honored by Function Apps.
 

Error in Text (error screenshot attached) : EventProcessorHost: Must start with a letter or number, and can contain only letters, numbers, and the dash (-) character. Every dash (-) character must be immediately preceded and followed by a letter or number; consecutive dashes are not permitted in container names. All letters in a container name must be lowercase. Must be from 3 to 63 characters long. Parameter name: leaseContainerName.

Please send updates on this bug request to jatinb@microsoft.com

**Comment by christopheranderson** [comment]
There is likely also portal issues here, Mike. Feel free to create them or sit down with me to create them.

**Comment by MikeStall** [comment]
This is a restriction coming from EventProcessorHost, the SDK  client provided by the EventHubs team. 
The error message is coming from there:
at Microsoft.ServiceBus.Messaging.EventProcessorHost.ValidateContainerName(String paramValue, String paramName)
   at Microsoft.ServiceBus.Messaging.EventProcessorHost.<InitializeAsync>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceBus.Messaging.EventProcessorHost.<StartAsync>d__16.MoveNext()

**Comment by MikeStall** [comment]
Here's what's going on: EventProcessorHost uses a storage container to coordinate between its multiple instances.  We use the default ctor that sets the container name to be the eventhub name. But event hub has different grammar rules than storage.  The exact grammar for eventhub names is not specified but it is generally more permissive than storage names. 

The Eventhub team would like to deprecate that default ctor and has asked that Functions determine a storage container name itself. The function that generates a storage name from an eventhub full path name must be one-to-one (injective) . 
1. The same eventhub name must land on the same storage name so that multiple instances can coordinate when listening on the same hub. 
2. collision free so that 2 different eventhub names don't end up on the same storage name and erroneously collaborating with each other. 

Also be aware that we need to use the event hub's full path name (namespace and event hub name) since the different eh could have the same event hub name in different namespaces. This is related to https://github.com/Azure/azure-webjobs-sdk/issues/817

**Comment by JatinBavishi** [comment]
Hello Mike,

Praburaj is requesting if you can delete the ReporFiles.zip from this github issue - https://github.com/Azure/azure-webjobs-sdk-script/issues/625
He has recycled the secrets. But still would like the files removed.

I tried removing the attachment earlier but it did not give me an option.

Thanks,

Jatin Bavishi | Azure App Service Support | Office: 469-775-2300 | M-F 11am - 8pm USA Central Time Zone
