### ISSUE TITLE
Ngen F# compiler and dependencies to reduce startup times

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#637]
From @mathewc (https://github.com/Azure/azure-webjobs-sdk-script/issues/600#issuecomment-242873863) 

One other thing: I've noticed that the F# compiler has about an 11 second startup time the first time an F# function is compiled in an app domain. Subsequent compilations in the same app domain don't seem to pay that cost.

@dsyme suggested using a [domain neutral assembly](http://stackoverflow.com/questions/3058110/what-are-the-steps-for-making-domain-neutral-assemblies)

**Comment by fabiocav** [comment]
Loading it as a domain neutral assembly would have limited impact since today, we're not creating additional appdomains and paying that cost multiple times over the life of the host (it would still help a bit if the ASP.NET appdomain is killed/restarted in the same w3wp process, but in a true cold start case, wouldn't solve the issue).
We're hitting this at startup when loading into the default appdomain, which is where we load all functions as well. We have similar issues with Roslyn JIT times and there's some work in progress for us to ngen those assemblies. We could do the same with F#.

**Comment by dsyme** [comment]
@fabiocav Yes, NGEN should solve this problem

**Comment by fabiocav** [comment]
Adding @tohling to this discussion since she is handling the work to ngen some of our dependencies in prod.

**Comment by lindydonna** [comment]
NGEN is in scope for RC, so we will add F# dependencies to the list. Once we've done more investigation, we'll see if this needs to be bumped to a different milestone.

**Comment by lindydonna** [comment]
@tohling Is this already complete?

**Comment by tohling** [comment]
Yes

**Comment by lindydonna** [comment]
Closing per @tohling's comment

**Comment by dsyme** [comment]
That's great news,, thanks @tohling
