### ISSUE TITLE
1.0.0-beta1-10398: host not running

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#699]
I just upgraded to the latest version of the functions scripthost  (v.1.0.0-beta1-10398). When I upgraded, the host restarts as normal and from the webjobs dashboard, the host appears to be running (has a "running" badge). However, when I click attempt to replay a function invocation, there is a message that says the host is not running.

#### Repro steps

Provide the steps required to reproduce the problem

1. Install v.1.0.0-beta1-10398 as [described here](https://github.com/Azure/azure-webjobs-sdk-script/wiki#option-2-no-http-functionwebhook-support). 
2. View the webjobs dashboard to confirm the host is running
3. Attempt to invoke or replay a function and you should see a message indicating the host IS NOT running

#### Expected behavior

I expect that the host is indeed running.

#### Actual behavior

The host is not running and there are no error messages in the output log available in the dashboard.

#### Known workarounds

Reverting to the previous version, 1.0.0-beta1-10355, resolves the issue.

#### Related information 

* My jobs are written in Node.js.
* I'm running the functions scripthost as [described here](https://github.com/Azure/azure-webjobs-sdk-script/wiki#option-2-no-http-functionwebhook-support).

**Comment by mathewc** [comment]
Can you check for any error logs in the logs directory of your site? When running in this mode, file logging is disabled by default. You can enable it by setting the `fileLoggingMode` option in host.json to "always" as described [here](https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json) Turning on file logging will cause log files to be written to `D:\home\LogFiles\Application\Functions`. Hopefully that shows us what the error is. There were some breaking changes in this release, so perhaps the issue is that your functions need to be updated to account for breaking changes.

**Comment by jamesdixon** [comment]
I can't tell you why, but when I reverted back to the latest version and enabled logging, suddenly everything started working again! 👍 

I'll let you know if I run into the issue again.

Thanks!

**Comment by mathewc** [comment]
Well, if you have time, see if things continue to work with file logging disabled (the default). It should. Otherwise there might be a bug we need to fix.
