### ISSUE TITLE
Node: Unhandled error events cause silent host restart

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#751]
This forum post shows an example where we silently restart the host if you're not watching an error event: https://social.msdn.microsoft.com/Forums/azure/en-US/7075f317-f4e2-490a-a4ba-cc423eb21ea4/creating-a-read-stream-to-a-missing-blob-causes-the-job-host-to-restart?forum=AzureFunctions

A concrete example:

    const azure = require('azure-storage');
    const blobSvc = azure.createBlobService(process.env['brettsamfunc_STORAGE']);

    module.exports = function(context, req) {    
        var readStream = blobSvc.createReadStream('repro', 'nonexistentfilename');
        readStream.on('end', function(){
            context.log('End!');
            context.done();
        });
    };

Assuming your storage account is fine, this will silently restart the job host.

If you add this, you'll handle the error and things will work okay:
    
    readStream.on('error', function(err){
        context.log('Error! ' + err);
        context.done();
    });

But that's really hard to decipher when you never see the `Unhandled 'error' event` message from node -- just host restarts.

**Comment by mathewc** [comment]
We register a Node global exception handler for these errors [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Content/Script/functions.js#L14). When an exception occurs, this causes a callback back into our handler [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Description/Node/NodeFunctionInvoker.cs#L576). The intent is that we log the error so user can see, then allow the error to kill the process.

Currently I think those errors are logged to the host logs only, since this is a global error. For async background errors like this, we don't have call stack to allow us to track the error back to a particular function.

We have some open issues to surface host level errors better. That might help.

**Comment by brettsam** [comment]
To be clear, I wasn't seeing the logs in Host or Function logs in this example. Host logs show...

    2016-10-06T14:59:41.440 Function started (Id=8f7f6cdc-e72b-4b8a-ae89-cfce4ea45aa2)
    2016-10-06T15:00:05.437 Reading host configuration file 'D:\home\site\wwwroot\host.json'

...which indicates that the host restarted after the function started. This is with verbose logging on as well (although that shouldn't really matter for this case).

**Comment by mathewc** [comment]
Then that is a bug in our exception handling / error reporting we need to address. I know this works on some paths - not sure what is going on here. I think we have e2e tests verifying we capture Node unhandled exceptions in some cases.

**Comment by mamaso** [comment]
Ok, played around with this a bit.  My theory is that these issues are due to node_modules folder location.  If node_modules doesn't exist at the script level we don't correlate those exceptions with a function, see [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Host/ScriptHost.cs#L963)

**Comment by mathewc** [comment]
Yes, the correlation logic relies on the source of the error (based on stack trace) containing the name of a function. In the case of global unhandled exceptions coming from modules outside of the function directory, there might not be anything we can do.

**Comment by mamaso** [comment]
@mathewc Do we restrict to stack trace for a reason?  It would be pretty simple to have the node invoker pass the function metadata along with the error so that all errors are correctly associated with functions without the stack trace logic, but is that too inclusive?

**Comment by mathewc** [comment]
The issue is that the global exception handler is static, and can't receive any per invocation state. So for global unhandled exceptions coming from code outside of the user's script, the stack trace won't contain the function directory, preventing us from doing an association. These errors are logged to the host log files though.

**Comment by mamaso** [comment]
Looked into this a bit more, the killed process is by design, which seems to be a reasonable response in this case: https://github.com/tjanczuk/edge/issues/444.
