### ISSUE TITLE
Error message from the WebJobs SDK (host?) dont show up in function error log

### ISSUE THREAD

**Issue by yochay** [Azure/azure-webjobs-sdk-script#95]
Using postman to test function. I forgot to change the content-type to application/json. 

I get the following error 

```
{
  "Message": "The WebHook request must contain an entity body formatted as JSON."
}
```

this error never shows up in the function log, because the function is not even triggered - not seeing the log entry...

This is somewhat confusion. As I expect that behind the scense the SDK do execute and runs the host, which blocks the function.

**Comment by mathewc** [comment]
You do see the error though in the Postman response body, right? I'd argue that issues like this for HTTP/WebHooks functions are not truly errors. Bad requests will happen from time to time, and I don't think external caller errors should show up in error logs (i.e the function is not in error). Similarly, it's not an error when requests fail authorization. 

BTW  the reason that doesn't get written to the function log is due to implementation details. That error is actually coming from the ASP.NET WebHooks library that we use for WebHook validation. That validation happens very early in the request pipeline, before the request even reaches the script runtime proper, and before we execute your function at all. We might be able to also force such http errors into the function log, but it wouldn't be very clean. Also, I'd argue that

**Comment by yochay** [comment]
For any given API, and you can argue Function are a form of (HTTP) APIs, I should be able to see failed login attempts, failed, wrong parameters, etc... whether it is part of the Function log or somewhere  else it is not clear. However, I do think these errors need to surface. I dont think it is a P1 for public preview

**Comment by christopheranderson** [comment]
Maybe this gets exposed in Log Level verbose?

**Comment by mathewc** [comment]
We now log http responses to host logs, so you should see a 401 logged in these cases.
