### ISSUE TITLE
Azure Functions: Input binding to DocumentDB DocumentClient functions broken?

### ISSUE THREAD

**Issue by lucabol** [Azure/azure-webjobs-sdk-script#984]
Subscription id: 818e194a-9bee-486f-9854-03b3be61170b
Function App name: FollowTheGuru
The dll refernced below is from: https://github.com/lucabol/FollowTheGuru

#### Repro steps

1. Open
https://ms.portal.azure.com/#blade/WebsitesExtension/FunctionsIFrameBlade/id/%2Fsubscriptions%2F818e194a-9bee-486f-9854-03b3be61170b%2Fresourcegroups%2FFollowTheGuru%2Fproviders%2FMicrosoft.Web%2Fsites%2FFollowTheGuru

#### Expected behavior

Compile and run fine.

#### Actual behavior

Crashes AppService.

#### Known workarounds

None.

**Comment by lucabol** [comment]
Easier repro steps.

Either download [this appservice](https://microsoft-my.sharepoint.com/personal/lucabol_microsoft_com/_layouts/15/guestaccess.aspx?guestaccesstoken=eRRF3vtLt44SnvkK%2f0tL69Kk2F%2fuedvfrNn7LZHtnP8%3d&docid=2_10841386edffa4e07be8c7b93decb4220&rev=1)  and upload it to debug.

Or create manually the following:
run.csx
--------------------

using System; 
using Microsoft.Azure.Documents;
using Microsoft.Azure.Documents.Client;

public static void Run(TimerInfo myTimer, DocumentClient client, TraceWriter log)
{
    log.Info($"C# Timer trigger function executed at: {DateTime.Now}");
   
}

project.json
------------------------

{  
  "frameworks": {
      "net46": {
        "dependencies": {
          "Microsoft.Azure.DocumentDB": "1.7.1"
        }
      }
   }
}

function.json
----------------------------

{
  "bindings": [
    {
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */5 * * * *"
    },
    {
      "type": "documentDB",
      "name": "client",
      "databaseName": "guru-portfolios",
      "collectionName": "lucabol",
      "id": "{documentId}",
      "connection": "guru-portfolios_DOCUMENTDB",
      "direction": "in"
    }
  ],
  "disabled": true
}

**Comment by stephlocke** [comment]
@lucabol I had some compilation errors - I needed an extra package in my project.json:
```
{  
  "frameworks": {
      "net46": {
        "dependencies": {
          "Microsoft.Azure.DocumentDB": "1.7.1",
          "Microsoft.Azure.WebJobs.Extensions.DocumentDB": "1.0.0-beta2"
        }
      }
   }
}
```

**Comment by lucabol** [comment]
Hi, adding that line in my project.json gives me exactly the same error as before. Do you see anything different?

**Comment by stephlocke** [comment]
Ah, also I was working off the info in [extensions repo](https://github.com/Azure/azure-webjobs-sdk-extensions) and my DocumentDB binding in my Function looks like:
```
[DocumentDB] DocumentClient client,
```

**Comment by lucabol** [comment]
Adding that attribute to the parameter, still gives me the same error. Can't you try reproing the problem using the project I attached, so we are on the same page?

**Comment by fabiocav** [comment]
@lucabol can you share the detailed error message you're getting?

**Comment by lucabol** [comment]
Below. btw: what do I do wrong that no-one runs my minimal repro? We would avoid all these back and forth. You'll see the error and come back here just when you have fixed it (or told me what I did wrong), instead of going back and forth like this.

Function ($UpdateGuruPortfolios) Error: Could not load file or assembly 'Microsoft.Azure.Documents.Client, Version=1.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040). Could not load file or assembly 'Microsoft.Azure.Documents.Client, Version=1.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040). 
Session Id: 6ca41521193b410b9e3b2e5af055c590
Timestamp: 2016-12-02T07:43:12.232Z

**Comment by fabiocav** [comment]
@lucabol, apologies for the delay. This issue has been triaged and resourced for investigation. The question above was an attempt to get some additional missing details to see if we could expedite the process before we're able to work with what you have provided to repro.

The message is indeed helpful and, looking at your current setup shows that you're referencing an old version of the DocumentDB client, which was causing an issue when binding to `DocumentClient` (which would also happen with other DocumentDB types as opposed to a POCO, JObject, etc.).

The DocumentDB binding exposes a shared assembly for the DocumentDB library, and that is the simplest way to reference the assembly and use its types.
In order to do that, you can delete your `project.json` (and lock file) as it won't be needed, and add the following reference to your function script file:
`#r "Microsoft.Azure.Documents.Client"`

That will automatically bring the appropriate assembly version and make those types available to your script.

**NOTE**: Your binding currently uses a `{documentId}` named input, which won't be available with the trigger you're using, so that named parameter will not be resolved. You can find more information about parameter binding here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#parameter-binding

**NOTE 2**: If your function app is in the state described in the original issue, you may need to restart it after deleting your `project.json`

**Comment by lucabol** [comment]
With all the changes described above, it now works. Thanks a bunch! Closing it. Perhaps documenting it somewhere would be nice (assuming I haven't missed an existing documentation).

**Comment by fabiocav** [comment]
Yes! I've reached out to @lindydonna and @christopheranderson as it looks like we've lost some documentation with the move to the new docs site. 
I've opened an issue to track that here: https://github.com/Azure/Azure-Functions/issues/89

Thank you for your patience with this! I'm glad to hear this is working for you.
